version: '2'
services:
 db:
  image: mysql:5.7
  #  ports:
  #  - "13306:3306"
  volumes:
   - "./.data/db:/var/lib/mysql"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASED: catalogo
   MYSQL_USER: root
   MYSQL_PASSWORD: bolacha
 web:
  volumes:
   - "./:/var/www/html"
  depends_on:
   - db
  image: tutum/lamp
  links:
   - db
  ports:
   - "80:80"
  restart: always
